display_name: humanizer-model-training
description: "Entraînement du modèle de humanisation de texte"

# Configuration du worker pool
worker_pool_specs:
  - machine_spec:
      machine_type: n1-standard-4
      accelerator_type: NVIDIA_TESLA_T4
      accelerator_count: 1
    replica_count: 1
    container_spec:
      image_uri: gcr.io/PROJECT_ID/ia-training:latest
      args:
        - "python"
        - "train_on_gcp.py"
      env:
        - name: GCS_BUCKET_NAME
          value: "your-bucket-name"
        - name: DOWNLOAD_FROM_GCS
          value: "true"
        - name: UPLOAD_TO_GCS
          value: "true"
        - name: BATCH_SIZE
          value: "16"
        - name: NUM_EPOCHS
          value: "5"
        - name: LEARNING_RATE
          value: "3e-5"
        - name: USE_TENSORBOARD
          value: "true"

# Configuration du réseau
network: projects/PROJECT_ID/global/networks/default

# Configuration des logs
base_output_directory:
  output_uri_prefix: gs://your-bucket-name/vertex-ai-training/

# Configuration des ressources
scheduling:
  timeout: 7200s  # 2 heures
  restart_job_on_worker_restart: false

# Configuration des métriques
tensorboard: gs://your-bucket-name/tensorboard/ 